# Generated by Django 6.1 on 2026-09-06 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='Citizen', max_length=150)),
                ('age_group', models.CharField(help_text='e.g. 18-25, 26-40, 41-59, 60+', max_length=50)),
                ('education_level', models.CharField(help_text='e.g. none, 10th_pass, 12th_pass, graduate, postgraduate', max_length=80)),
                ('occupation', models.CharField(help_text='e.g. student, farmer, business_owner, salaried, unemployed, gig_worker', max_length=80)),
                ('state', models.CharField(help_text='State or Union Territory', max_length=80)),
                ('income_bracket', models.CharField(help_text='e.g. bpl, low_income, lower_middle, middle, higher', max_length=80)),
                ('specific_category', models.CharField(help_text='e.g. general, obc, sc, st, pwd, woman_entrepreneur, minority', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short code e.g. PM-KISAN', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Official Scheme Full Title', max_length=255)),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('ministry', models.CharField(help_text='Administering Ministry or Department', max_length=255)),
                ('level', models.CharField(choices=[('CENTRAL', 'Central Government (All-India)'), ('STATE', 'State Government Specific')], default='CENTRAL', max_length=20)),
                ('state_scope', models.CharField(default='ALL', help_text="'ALL' or specific state name", max_length=100)),
                ('sector_category', models.CharField(default='General', help_text='Agriculture, Education, Business, Health, Social Welfare, Housing', max_length=100)),
                ('benefit_highlight', models.CharField(help_text='Key benefit e.g. ₹6,000 / year DBT or 35% Capital Subsidy', max_length=255)),
                ('legal_description', models.TextField(help_text='Original gazette / statutory legal text')),
                ('plain_language_summary', models.TextField(help_text='Simplified conversational summary for citizens')),
                ('plain_language_eligibility', models.TextField(help_text='Simplified bullet points for citizen criteria')),
                ('application_process', models.TextField(help_text='Markdown or JSON step-by-step application instructions')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('deadline_text', models.CharField(default='Open Throughout Year', max_length=100)),
                ('official_portal_name', models.CharField(default='National Portal of India', max_length=150)),
                ('official_portal_url', models.URLField(max_length=500)),
                ('helpline_number', models.CharField(blank=True, default='1800-115-555', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags e.g. farmer, subsidy, direct_benefit', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('applicant_name', models.CharField(max_length=150)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('current_status', models.CharField(choices=[('SUBMITTED', 'Application Submitted'), ('DOCUMENT_VERIFICATION', 'Document Verification in Progress'), ('FIELD_INSPECTION', 'Field / Physical Inspection'), ('SANCTIONED', 'Sanction Order Generated'), ('DISBURSED', 'Benefit Disbursed / Disbursal Pending'), ('ACTION_REQUIRED', 'Citizen Action Required (Missing Document)'), ('REJECTED', 'Application Rejected / Non-Eligible')], default='SUBMITTED', max_length=30)),
                ('status_summary', models.CharField(default='Application under primary scrutiny', max_length=255)),
                ('official_portal_ref', models.CharField(blank=True, help_text='Government backend reference ID', max_length=100)),
                ('benefit_amount', models.CharField(blank=True, default='Pending Sanction', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('citizen_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemes.citizenprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schemes.scheme')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('STATUS_UPDATE', 'Application Status Update'), ('DEADLINE_REMINDER', 'Scheme Deadline Reminder'), ('NEW_SCHEME', 'New Scheme Alert'), ('ACTION_REQUIRED', 'Action Required / Document Request')], default='STATUS_UPDATE', max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('SMS', 'SMS Alert'), ('WHATSAPP', 'WhatsApp Official Alert'), ('EMAIL', 'Email Notification')], default='IN_APP', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='#', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemes.applicationrecord')),
                ('citizen_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemes.citizenprofile')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemes.scheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_field', models.CharField(choices=[('age_group', 'Age Group'), ('education_level', 'Education Level'), ('occupation', 'Occupation / Profession'), ('state', 'State / Region'), ('income_bracket', 'Income Bracket'), ('specific_category', 'Specific Category / Social Status')], max_length=50)),
                ('operator', models.CharField(choices=[('in', 'Is in list'), ('not_in', 'Is not in list'), ('eq', 'Equals'), ('any', 'Applies to any / All eligible')], default='in', max_length=20)),
                ('expected_values', models.TextField(help_text='JSON or comma-separated list of matching values')),
                ('legal_clause_text', models.TextField(blank=True, help_text='Verbatim legal gazette clause')),
                ('plain_language_rule', models.CharField(help_text='Plain conversational explanation for citizen', max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=150)),
                ('why_required', models.CharField(help_text='Clear citizen-friendly reason why this is needed', max_length=255)),
                ('issuing_authority', models.CharField(default='Competent State / Central Authority', max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('digilocker_available', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('SUBMITTED', 'Application Submitted'), ('DOCUMENT_VERIFICATION', 'Document Verification in Progress'), ('FIELD_INSPECTION', 'Field / Physical Inspection'), ('SANCTIONED', 'Sanction Order Generated'), ('DISBURSED', 'Benefit Disbursed / Disbursal Pending'), ('ACTION_REQUIRED', 'Citizen Action Required (Missing Document)'), ('REJECTED', 'Application Rejected / Non-Eligible')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('officer_remarks', models.TextField(help_text='Official remarks or clear guidance for next step')),
                ('action_required_note', models.TextField(blank=True, help_text='Action citizen must take if any', null=True)),
                ('updated_by', models.CharField(default='District Nodal Verification Cell', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='schemes.applicationrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
